# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giaodienindex.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 447)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.489, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(138, 138, 142, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tieude = QtWidgets.QLabel(self.centralwidget)
        self.tieude.setGeometry(QtCore.QRect(190, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tieude.setFont(font)
        self.tieude.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.tieude.setObjectName("tieude")
        self.ptn_nhandien_dangnhap = QtWidgets.QPushButton(self.centralwidget)
        self.ptn_nhandien_dangnhap.setGeometry(QtCore.QRect(190, 130, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ptn_nhandien_dangnhap.setFont(font)
        self.ptn_nhandien_dangnhap.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 100), stop:1 rgba(255, 255, 255, 50));\n"
"color: rgb(255, 255, 255);")
        self.ptn_nhandien_dangnhap.setObjectName("ptn_nhandien_dangnhap")
        self.ptn_nhandien_dangky = QtWidgets.QPushButton(self.centralwidget)
        self.ptn_nhandien_dangky.setGeometry(QtCore.QRect(190, 212, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ptn_nhandien_dangky.setFont(font)
        self.ptn_nhandien_dangky.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 100), stop:1 rgba(255, 255, 255, 50));\n"
"color: rgb(255, 255, 255);")
        self.ptn_nhandien_dangky.setObjectName("ptn_nhandien_dangky")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 498, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tieude.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.ptn_nhandien_dangnhap.setText(_translate("MainWindow", "Bấm để nhận diện"))
        self.ptn_nhandien_dangky.setText(_translate("MainWindow", "Bấm để đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
